language: node_js
node_js:
    - lts/*
branches:
    only:
        - gh-pages #默认情况下，gh-pages除非将其添加到安全列表中，否则不会构建该分支。
install:
    - npm i
script:
    - npm run build
deploy:
    provider: pages
    strategy: git
    cleanup: true
    local_dir: docs/.vuepress/dist
    token: ${GITHUB_TOKEN} # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
    keep_history: true
    on:
        branch: master
